version: "3"
services:
    urady-node-service:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PORT=5000
        depends_on:
            - db

    db:
        container_name: ajira_postgres_jobs_container
        image: postgres
        restart: unless-stopped
        volumes:
            - ajira_db_data:/data/postgres
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5434:5432 #host:container
    adminer: #admin console for the db
        depends_on:
            - db
        image: adminer
        restart: always
        ports:
            - 8082:8080
volumes:
    urady_db_data: {}
